//
// Generated by JavaToPas v1.5 20150831 - 132309
////////////////////////////////////////////////////////////////////////////////

// Contains
// android.nfc.cardemulation.CardEmulation
// android.nfc.cardemulation.HostApduService
// android.nfc.cardemulation.OffHostApduService

unit Androidapi.JNI.NFC.CardEmulation;

interface

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.NfcAdapter,
//  android.content.ComponentName,
//  android.app.Activity;
//
//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  Androidapi.JNI.os,
//  android.content.ClipData;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  Androidapi.JNI.os,
//  android.content.ClipData;

type
  JCardEmulation = interface;

  JCardEmulationClass = interface(JObjectClass)
    ['{5AFA3C6F-2427-4560-8945-D33D1327A8CC}']
    function _GetACTION_CHANGE_DEFAULT : JString; cdecl;                        //  A: $19
    function _GetCATEGORY_OTHER : JString; cdecl;                               //  A: $19
    function _GetCATEGORY_PAYMENT : JString; cdecl;                             //  A: $19
    function _GetEXTRA_CATEGORY : JString; cdecl;                               //  A: $19
    function _GetEXTRA_SERVICE_COMPONENT : JString; cdecl;                      //  A: $19
    function _GetSELECTION_MODE_ALWAYS_ASK : Integer; cdecl;                    //  A: $19
    function _GetSELECTION_MODE_ASK_IF_CONFLICT : Integer; cdecl;               //  A: $19
    function _GetSELECTION_MODE_PREFER_DEFAULT : Integer; cdecl;                //  A: $19
    function categoryAllowsForegroundPreference(category : JString) : boolean; cdecl;// (Ljava/lang/String;)Z A: $1
    function getAidsForService(service : JComponentName; category : JString) : JList; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Ljava/util/List; A: $1
    function getInstance(adapter : JNfcAdapter) : JCardEmulation; cdecl;        // (Landroid/nfc/NfcAdapter;)Landroid/nfc/cardemulation/CardEmulation; A: $29
    function getSelectionModeForCategory(category : JString) : Integer; cdecl;  // (Ljava/lang/String;)I A: $1
    function isDefaultServiceForAid(service : JComponentName; aid : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function isDefaultServiceForCategory(service : JComponentName; category : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function registerAidsForService(service : JComponentName; category : JString; aids : JList) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;Ljava/util/List;)Z A: $1
    function removeAidsForService(service : JComponentName; category : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function setPreferredService(activity : JActivity; service : JComponentName) : boolean; cdecl;// (Landroid/app/Activity;Landroid/content/ComponentName;)Z A: $1
    function supportsAidPrefixRegistration : boolean; cdecl;                    // ()Z A: $1
    function unsetPreferredService(activity : JActivity) : boolean; cdecl;      // (Landroid/app/Activity;)Z A: $1
    property ACTION_CHANGE_DEFAULT : JString read _GetACTION_CHANGE_DEFAULT;    // Ljava/lang/String; A: $19
    property CATEGORY_OTHER : JString read _GetCATEGORY_OTHER;                  // Ljava/lang/String; A: $19
    property CATEGORY_PAYMENT : JString read _GetCATEGORY_PAYMENT;              // Ljava/lang/String; A: $19
    property EXTRA_CATEGORY : JString read _GetEXTRA_CATEGORY;                  // Ljava/lang/String; A: $19
    property EXTRA_SERVICE_COMPONENT : JString read _GetEXTRA_SERVICE_COMPONENT;// Ljava/lang/String; A: $19
    property SELECTION_MODE_ALWAYS_ASK : Integer read _GetSELECTION_MODE_ALWAYS_ASK;// I A: $19
    property SELECTION_MODE_ASK_IF_CONFLICT : Integer read _GetSELECTION_MODE_ASK_IF_CONFLICT;// I A: $19
    property SELECTION_MODE_PREFER_DEFAULT : Integer read _GetSELECTION_MODE_PREFER_DEFAULT;// I A: $19
  end;

  [JavaSignature('android/nfc/cardemulation/CardEmulation')]
  JCardEmulation = interface(JObject)
    ['{13EDDC3F-34B3-47B3-A2E8-E23E5104FB91}']
    function categoryAllowsForegroundPreference(category : JString) : boolean; cdecl;// (Ljava/lang/String;)Z A: $1
    function getAidsForService(service : JComponentName; category : JString) : JList; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Ljava/util/List; A: $1
    function getSelectionModeForCategory(category : JString) : Integer; cdecl;  // (Ljava/lang/String;)I A: $1
    function isDefaultServiceForAid(service : JComponentName; aid : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function isDefaultServiceForCategory(service : JComponentName; category : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function registerAidsForService(service : JComponentName; category : JString; aids : JList) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;Ljava/util/List;)Z A: $1
    function removeAidsForService(service : JComponentName; category : JString) : boolean; cdecl;// (Landroid/content/ComponentName;Ljava/lang/String;)Z A: $1
    function setPreferredService(activity : JActivity; service : JComponentName) : boolean; cdecl;// (Landroid/app/Activity;Landroid/content/ComponentName;)Z A: $1
    function supportsAidPrefixRegistration : boolean; cdecl;                    // ()Z A: $1
    function unsetPreferredService(activity : JActivity) : boolean; cdecl;      // (Landroid/app/Activity;)Z A: $1
  end;

  TJCardEmulation = class(TJavaGenericImport<JCardEmulationClass, JCardEmulation>)
  end;

const
  TJCardEmulationACTION_CHANGE_DEFAULT = 'android.nfc.cardemulation.action.ACTION_CHANGE_DEFAULT';
  TJCardEmulationCATEGORY_OTHER = 'other';
  TJCardEmulationCATEGORY_PAYMENT = 'payment';
  TJCardEmulationEXTRA_CATEGORY = 'category';
  TJCardEmulationEXTRA_SERVICE_COMPONENT = 'component';
  TJCardEmulationSELECTION_MODE_ALWAYS_ASK = 1;
  TJCardEmulationSELECTION_MODE_ASK_IF_CONFLICT = 2;
  TJCardEmulationSELECTION_MODE_PREFER_DEFAULT = 0;

type
  JHostApduService = interface;

  JHostApduServiceClass = interface(JObjectClass)
    ['{02652582-648B-46C3-8AE3-B13F0AEE1EF0}']
    function _GetDEACTIVATION_DESELECTED : Integer; cdecl;                      //  A: $19
    function _GetDEACTIVATION_LINK_LOSS : Integer; cdecl;                       //  A: $19
    function _GetSERVICE_INTERFACE : JString; cdecl;                            //  A: $19
    function _GetSERVICE_META_DATA : JString; cdecl;                            //  A: $19
    function init : JHostApduService; cdecl;                                    // ()V A: $1
    function onBind(intent : JIntent) : JIBinder; cdecl;                        // (Landroid/content/Intent;)Landroid/os/IBinder; A: $11
    function processCommandApdu(TJavaArrayByteparam0 : TJavaArray<Byte>; JBundleparam1 : JBundle) : TJavaArray<Byte>; cdecl;// ([BLandroid/os/Bundle;)[B A: $401
    procedure notifyUnhandled ; cdecl;                                          // ()V A: $11
    procedure onDeactivated(Integerparam0 : Integer) ; cdecl;                   // (I)V A: $401
    procedure sendResponseApdu(responseApdu : TJavaArray<Byte>) ; cdecl;        // ([B)V A: $11
    property DEACTIVATION_DESELECTED : Integer read _GetDEACTIVATION_DESELECTED;// I A: $19
    property DEACTIVATION_LINK_LOSS : Integer read _GetDEACTIVATION_LINK_LOSS;  // I A: $19
    property SERVICE_INTERFACE : JString read _GetSERVICE_INTERFACE;            // Ljava/lang/String; A: $19
    property SERVICE_META_DATA : JString read _GetSERVICE_META_DATA;            // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/nfc/cardemulation/HostApduService')]
  JHostApduService = interface(JObject)
    ['{DF4C91BB-B7D3-4D90-B76F-172218C50A2B}']
    function processCommandApdu(TJavaArrayByteparam0 : TJavaArray<Byte>; JBundleparam1 : JBundle) : TJavaArray<Byte>; cdecl;// ([BLandroid/os/Bundle;)[B A: $401
    procedure onDeactivated(Integerparam0 : Integer) ; cdecl;                   // (I)V A: $401
  end;

  TJHostApduService = class(TJavaGenericImport<JHostApduServiceClass, JHostApduService>)
  end;

const
  TJHostApduServiceDEACTIVATION_DESELECTED = 1;
  TJHostApduServiceDEACTIVATION_LINK_LOSS = 0;
  TJHostApduServiceSERVICE_INTERFACE = 'android.nfc.cardemulation.action.HOST_APDU_SERVICE';
  TJHostApduServiceSERVICE_META_DATA = 'android.nfc.cardemulation.host_apdu_service';

type
  JOffHostApduService = interface;

  JOffHostApduServiceClass = interface(JObjectClass)
    ['{A82879CE-CC77-491E-A584-EEA6E914C8AD}']
    function _GetSERVICE_INTERFACE : JString; cdecl;                            //  A: $19
    function _GetSERVICE_META_DATA : JString; cdecl;                            //  A: $19
    function init : JOffHostApduService; cdecl;                                 // ()V A: $1
    function onBind(JIntentparam0 : JIntent) : JIBinder; cdecl;                 // (Landroid/content/Intent;)Landroid/os/IBinder; A: $401
    property SERVICE_INTERFACE : JString read _GetSERVICE_INTERFACE;            // Ljava/lang/String; A: $19
    property SERVICE_META_DATA : JString read _GetSERVICE_META_DATA;            // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/nfc/cardemulation/OffHostApduService')]
  JOffHostApduService = interface(JObject)
    ['{5BAC7C52-5AC7-460F-A15E-A7AC7E37F960}']
    function onBind(JIntentparam0 : JIntent) : JIBinder; cdecl;                 // (Landroid/content/Intent;)Landroid/os/IBinder; A: $401
  end;

  TJOffHostApduService = class(TJavaGenericImport<JOffHostApduServiceClass, JOffHostApduService>)
  end;

const
  TJOffHostApduServiceSERVICE_INTERFACE = 'android.nfc.cardemulation.action.OFF_HOST_APDU_SERVICE';
  TJOffHostApduServiceSERVICE_META_DATA = 'android.nfc.cardemulation.off_host_apdu_service';

implementation

end.
