//
// Generated by JavaToPas v1.5 20150831 - 132310
////////////////////////////////////////////////////////////////////////////////

// Contains
// android.nfc.tech.BasicTagTechnology
// android.nfc.tech.IsoDep
// android.nfc.tech.MifareClassic
// android.nfc.tech.MifareUltralight
// android.nfc.tech.Ndef
// android.nfc.tech.NdefFormatable
// android.nfc.tech.NfcA
// android.nfc.tech.NfcB
// android.nfc.tech.NfcBarcode
// android.nfc.tech.NfcF
// android.nfc.tech.NfcV
// android.nfc.tech.TagTechnology

unit Androidapi.JNI.NFC.Tech;

interface

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag,
//  android.nfc.NdefMessage;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag,
//  android.nfc.NdefMessage;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

//uses
//  AndroidAPI.JNIBridge,
//  Androidapi.JNI.JavaTypes,
//  android.nfc.Tag;

type
  JBasicTagTechnology = interface;

  JBasicTagTechnologyClass = interface(JObjectClass)
    ['{FA946A5E-1A9E-494B-8B47-FAB567E0B837}']
    function getTag : JTag; cdecl;                                              // ()Landroid/nfc/Tag; A: $1
    function isConnected : boolean; cdecl;                                      // ()Z A: $1
    procedure close ; cdecl;                                                    // ()V A: $1
    procedure connect ; cdecl;                                                  // ()V A: $1
  end;

  [JavaSignature('android/nfc/tech/BasicTagTechnology')]
  JBasicTagTechnology = interface(JObject)
    ['{7EF35D45-A034-4C4E-BB61-755FDA8ABA9E}']
    function getTag : JTag; cdecl;                                              // ()Landroid/nfc/Tag; A: $1
    function isConnected : boolean; cdecl;                                      // ()Z A: $1
    procedure close ; cdecl;                                                    // ()V A: $1
    procedure connect ; cdecl;                                                  // ()V A: $1
  end;

  TJBasicTagTechnology = class(TJavaGenericImport<JBasicTagTechnologyClass, JBasicTagTechnology>)
  end;

type
  JIsoDep = interface;

  JIsoDepClass = interface(JObjectClass)
    ['{332E2C73-D68D-4487-A7EF-752D1CB11ADB}']
    function get(tag : JTag) : JIsoDep; cdecl;                                  // (Landroid/nfc/Tag;)Landroid/nfc/tech/IsoDep; A: $9
    function getHiLayerResponse : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getHistoricalBytes : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function isExtendedLengthApduSupported : boolean; cdecl;                    // ()Z A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  [JavaSignature('android/nfc/tech/IsoDep')]
  JIsoDep = interface(JObject)
    ['{2CFF165C-3DF6-4574-BCA9-35CD9682AD38}']
    function getHiLayerResponse : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getHistoricalBytes : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function isExtendedLengthApduSupported : boolean; cdecl;                    // ()Z A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  TJIsoDep = class(TJavaGenericImport<JIsoDepClass, JIsoDep>)
  end;

type
  JMifareClassic = interface;

  JMifareClassicClass = interface(JObjectClass)
    ['{33299AAA-C7A3-432B-BDE7-4A984D902275}']
    function _GetBLOCK_SIZE : Integer; cdecl;                                   //  A: $19
    function _GetKEY_DEFAULT : TJavaArray<Byte>; cdecl;                         //  A: $19
    function _GetKEY_MIFARE_APPLICATION_DIRECTORY : TJavaArray<Byte>; cdecl;    //  A: $19
    function _GetKEY_NFC_FORUM : TJavaArray<Byte>; cdecl;                       //  A: $19
    function _GetSIZE_1K : Integer; cdecl;                                      //  A: $19
    function _GetSIZE_2K : Integer; cdecl;                                      //  A: $19
    function _GetSIZE_4K : Integer; cdecl;                                      //  A: $19
    function _GetSIZE_MINI : Integer; cdecl;                                    //  A: $19
    function _GetTYPE_CLASSIC : Integer; cdecl;                                 //  A: $19
    function _GetTYPE_PLUS : Integer; cdecl;                                    //  A: $19
    function _GetTYPE_PRO : Integer; cdecl;                                     //  A: $19
    function _GetTYPE_UNKNOWN : Integer; cdecl;                                 //  A: $19
    function authenticateSectorWithKeyA(sectorIndex : Integer; key : TJavaArray<Byte>) : boolean; cdecl;// (I[B)Z A: $1
    function authenticateSectorWithKeyB(sectorIndex : Integer; key : TJavaArray<Byte>) : boolean; cdecl;// (I[B)Z A: $1
    function blockToSector(blockIndex : Integer) : Integer; cdecl;              // (I)I A: $1
    function get(tag : JTag) : JMifareClassic; cdecl;                           // (Landroid/nfc/Tag;)Landroid/nfc/tech/MifareClassic; A: $9
    function getBlockCount : Integer; cdecl;                                    // ()I A: $1
    function getBlockCountInSector(sectorIndex : Integer) : Integer; cdecl;     // (I)I A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSectorCount : Integer; cdecl;                                   // ()I A: $1
    function getSize : Integer; cdecl;                                          // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
    function readBlock(blockIndex : Integer) : TJavaArray<Byte>; cdecl;         // (I)[B A: $1
    function sectorToBlock(sectorIndex : Integer) : Integer; cdecl;             // (I)I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure decrement(blockIndex : Integer; value : Integer) ; cdecl;         // (II)V A: $1
    procedure increment(blockIndex : Integer; value : Integer) ; cdecl;         // (II)V A: $1
    procedure restore(blockIndex : Integer) ; cdecl;                            // (I)V A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
    procedure transfer(blockIndex : Integer) ; cdecl;                           // (I)V A: $1
    procedure writeBlock(blockIndex : Integer; data : TJavaArray<Byte>) ; cdecl;// (I[B)V A: $1
    property BLOCK_SIZE : Integer read _GetBLOCK_SIZE;                          // I A: $19
    property KEY_DEFAULT : TJavaArray<Byte> read _GetKEY_DEFAULT;               // [B A: $19
    property KEY_MIFARE_APPLICATION_DIRECTORY : TJavaArray<Byte> read _GetKEY_MIFARE_APPLICATION_DIRECTORY;// [B A: $19
    property KEY_NFC_FORUM : TJavaArray<Byte> read _GetKEY_NFC_FORUM;           // [B A: $19
    property SIZE_1K : Integer read _GetSIZE_1K;                                // I A: $19
    property SIZE_2K : Integer read _GetSIZE_2K;                                // I A: $19
    property SIZE_4K : Integer read _GetSIZE_4K;                                // I A: $19
    property SIZE_MINI : Integer read _GetSIZE_MINI;                            // I A: $19
    property TYPE_CLASSIC : Integer read _GetTYPE_CLASSIC;                      // I A: $19
    property TYPE_PLUS : Integer read _GetTYPE_PLUS;                            // I A: $19
    property TYPE_PRO : Integer read _GetTYPE_PRO;                              // I A: $19
    property TYPE_UNKNOWN : Integer read _GetTYPE_UNKNOWN;                      // I A: $19
  end;

  [JavaSignature('android/nfc/tech/MifareClassic')]
  JMifareClassic = interface(JObject)
    ['{FF2C0A95-B221-4F00-9FC4-E9B8C382A93E}']
    function authenticateSectorWithKeyA(sectorIndex : Integer; key : TJavaArray<Byte>) : boolean; cdecl;// (I[B)Z A: $1
    function authenticateSectorWithKeyB(sectorIndex : Integer; key : TJavaArray<Byte>) : boolean; cdecl;// (I[B)Z A: $1
    function blockToSector(blockIndex : Integer) : Integer; cdecl;              // (I)I A: $1
    function getBlockCount : Integer; cdecl;                                    // ()I A: $1
    function getBlockCountInSector(sectorIndex : Integer) : Integer; cdecl;     // (I)I A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSectorCount : Integer; cdecl;                                   // ()I A: $1
    function getSize : Integer; cdecl;                                          // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
    function readBlock(blockIndex : Integer) : TJavaArray<Byte>; cdecl;         // (I)[B A: $1
    function sectorToBlock(sectorIndex : Integer) : Integer; cdecl;             // (I)I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure decrement(blockIndex : Integer; value : Integer) ; cdecl;         // (II)V A: $1
    procedure increment(blockIndex : Integer; value : Integer) ; cdecl;         // (II)V A: $1
    procedure restore(blockIndex : Integer) ; cdecl;                            // (I)V A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
    procedure transfer(blockIndex : Integer) ; cdecl;                           // (I)V A: $1
    procedure writeBlock(blockIndex : Integer; data : TJavaArray<Byte>) ; cdecl;// (I[B)V A: $1
  end;

  TJMifareClassic = class(TJavaGenericImport<JMifareClassicClass, JMifareClassic>)
  end;

const
  TJMifareClassicBLOCK_SIZE = 16;
  TJMifareClassicSIZE_1K = 1024;
  TJMifareClassicSIZE_2K = 2048;
  TJMifareClassicSIZE_4K = 4096;
  TJMifareClassicSIZE_MINI = 320;
  TJMifareClassicTYPE_CLASSIC = 0;
  TJMifareClassicTYPE_PLUS = 1;
  TJMifareClassicTYPE_PRO = 2;
  TJMifareClassicTYPE_UNKNOWN = -1;

type
  JMifareUltralight = interface;

  JMifareUltralightClass = interface(JObjectClass)
    ['{75CBE28C-FB17-46D7-8F40-94CE100687A2}']
    function _GetPAGE_SIZE : Integer; cdecl;                                    //  A: $19
    function _GetTYPE_ULTRALIGHT : Integer; cdecl;                              //  A: $19
    function _GetTYPE_ULTRALIGHT_C : Integer; cdecl;                            //  A: $19
    function _GetTYPE_UNKNOWN : Integer; cdecl;                                 //  A: $19
    function get(tag : JTag) : JMifareUltralight; cdecl;                        // (Landroid/nfc/Tag;)Landroid/nfc/tech/MifareUltralight; A: $9
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
    function readPages(pageOffset : Integer) : TJavaArray<Byte>; cdecl;         // (I)[B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
    procedure writePage(pageOffset : Integer; data : TJavaArray<Byte>) ; cdecl; // (I[B)V A: $1
    property PAGE_SIZE : Integer read _GetPAGE_SIZE;                            // I A: $19
    property TYPE_ULTRALIGHT : Integer read _GetTYPE_ULTRALIGHT;                // I A: $19
    property TYPE_ULTRALIGHT_C : Integer read _GetTYPE_ULTRALIGHT_C;            // I A: $19
    property TYPE_UNKNOWN : Integer read _GetTYPE_UNKNOWN;                      // I A: $19
  end;

  [JavaSignature('android/nfc/tech/MifareUltralight')]
  JMifareUltralight = interface(JObject)
    ['{12DF9A1B-C8C4-4DE5-824C-307EFADB7DB3}']
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
    function readPages(pageOffset : Integer) : TJavaArray<Byte>; cdecl;         // (I)[B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
    procedure writePage(pageOffset : Integer; data : TJavaArray<Byte>) ; cdecl; // (I[B)V A: $1
  end;

  TJMifareUltralight = class(TJavaGenericImport<JMifareUltralightClass, JMifareUltralight>)
  end;

const
  TJMifareUltralightPAGE_SIZE = 4;
  TJMifareUltralightTYPE_ULTRALIGHT = 1;
  TJMifareUltralightTYPE_ULTRALIGHT_C = 2;
  TJMifareUltralightTYPE_UNKNOWN = -1;

type
  JNdef = interface;

  JNdefClass = interface(JObjectClass)
    ['{0C14382A-559B-4886-8A53-E15C17CD4C76}']
    function _GetMIFARE_CLASSIC : JString; cdecl;                               //  A: $19
    function _GetNFC_FORUM_TYPE_1 : JString; cdecl;                             //  A: $19
    function _GetNFC_FORUM_TYPE_2 : JString; cdecl;                             //  A: $19
    function _GetNFC_FORUM_TYPE_3 : JString; cdecl;                             //  A: $19
    function _GetNFC_FORUM_TYPE_4 : JString; cdecl;                             //  A: $19
    function canMakeReadOnly : boolean; cdecl;                                  // ()Z A: $1
    function get(tag : JTag) : JNdef; cdecl;                                    // (Landroid/nfc/Tag;)Landroid/nfc/tech/Ndef; A: $9
    function getCachedNdefMessage : JNdefMessage; cdecl;                        // ()Landroid/nfc/NdefMessage; A: $1
    function getMaxSize : Integer; cdecl;                                       // ()I A: $1
    function getNdefMessage : JNdefMessage; cdecl;                              // ()Landroid/nfc/NdefMessage; A: $1
    function getType : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function isWritable : boolean; cdecl;                                       // ()Z A: $1
    function makeReadOnly : boolean; cdecl;                                     // ()Z A: $1
    procedure writeNdefMessage(msg : JNdefMessage) ; cdecl;                     // (Landroid/nfc/NdefMessage;)V A: $1
    property MIFARE_CLASSIC : JString read _GetMIFARE_CLASSIC;                  // Ljava/lang/String; A: $19
    property NFC_FORUM_TYPE_1 : JString read _GetNFC_FORUM_TYPE_1;              // Ljava/lang/String; A: $19
    property NFC_FORUM_TYPE_2 : JString read _GetNFC_FORUM_TYPE_2;              // Ljava/lang/String; A: $19
    property NFC_FORUM_TYPE_3 : JString read _GetNFC_FORUM_TYPE_3;              // Ljava/lang/String; A: $19
    property NFC_FORUM_TYPE_4 : JString read _GetNFC_FORUM_TYPE_4;              // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/nfc/tech/Ndef')]
  JNdef = interface(JObject)
    ['{6D0E457B-8B67-493D-9B7B-E8744F884C23}']
    function canMakeReadOnly : boolean; cdecl;                                  // ()Z A: $1
    function getCachedNdefMessage : JNdefMessage; cdecl;                        // ()Landroid/nfc/NdefMessage; A: $1
    function getMaxSize : Integer; cdecl;                                       // ()I A: $1
    function getNdefMessage : JNdefMessage; cdecl;                              // ()Landroid/nfc/NdefMessage; A: $1
    function getType : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function isWritable : boolean; cdecl;                                       // ()Z A: $1
    function makeReadOnly : boolean; cdecl;                                     // ()Z A: $1
    procedure writeNdefMessage(msg : JNdefMessage) ; cdecl;                     // (Landroid/nfc/NdefMessage;)V A: $1
  end;

  TJNdef = class(TJavaGenericImport<JNdefClass, JNdef>)
  end;

const
  TJNdefMIFARE_CLASSIC = 'com.nxp.ndef.mifareclassic';
  TJNdefNFC_FORUM_TYPE_1 = 'org.nfcforum.ndef.type1';
  TJNdefNFC_FORUM_TYPE_2 = 'org.nfcforum.ndef.type2';
  TJNdefNFC_FORUM_TYPE_3 = 'org.nfcforum.ndef.type3';
  TJNdefNFC_FORUM_TYPE_4 = 'org.nfcforum.ndef.type4';

type
  JNdefFormatable = interface;

  JNdefFormatableClass = interface(JObjectClass)
    ['{3CB4EF04-EF36-48F8-983B-9312BB8ADB0F}']
    function get(tag : JTag) : JNdefFormatable; cdecl;                          // (Landroid/nfc/Tag;)Landroid/nfc/tech/NdefFormatable; A: $9
    procedure format(firstMessage : JNdefMessage) ; cdecl;                      // (Landroid/nfc/NdefMessage;)V A: $1
    procedure formatReadOnly(firstMessage : JNdefMessage) ; cdecl;              // (Landroid/nfc/NdefMessage;)V A: $1
  end;

  [JavaSignature('android/nfc/tech/NdefFormatable')]
  JNdefFormatable = interface(JObject)
    ['{78E2F001-71C0-4567-816A-AC9A632EFBC2}']
    procedure format(firstMessage : JNdefMessage) ; cdecl;                      // (Landroid/nfc/NdefMessage;)V A: $1
    procedure formatReadOnly(firstMessage : JNdefMessage) ; cdecl;              // (Landroid/nfc/NdefMessage;)V A: $1
  end;

  TJNdefFormatable = class(TJavaGenericImport<JNdefFormatableClass, JNdefFormatable>)
  end;

type
  JNfcA = interface;

  JNfcAClass = interface(JObjectClass)
    ['{F0BC0FD5-7425-491F-9F41-136D4B0EBB14}']
    function get(tag : JTag) : JNfcA; cdecl;                                    // (Landroid/nfc/Tag;)Landroid/nfc/tech/NfcA; A: $9
    function getAtqa : TJavaArray<Byte>; cdecl;                                 // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSak : SmallInt; cdecl;                                          // ()S A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  [JavaSignature('android/nfc/tech/NfcA')]
  JNfcA = interface(JObject)
    ['{B03006B9-9EA1-4874-B624-091AEFD77319}']
    function getAtqa : TJavaArray<Byte>; cdecl;                                 // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSak : SmallInt; cdecl;                                          // ()S A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  TJNfcA = class(TJavaGenericImport<JNfcAClass, JNfcA>)
  end;

type
  JNfcB = interface;

  JNfcBClass = interface(JObjectClass)
    ['{CE3FD978-CF6C-4DDD-9C15-6272CC33201F}']
    function get(tag : JTag) : JNfcB; cdecl;                                    // (Landroid/nfc/Tag;)Landroid/nfc/tech/NfcB; A: $9
    function getApplicationData : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getProtocolInfo : TJavaArray<Byte>; cdecl;                         // ()[B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
  end;

  [JavaSignature('android/nfc/tech/NfcB')]
  JNfcB = interface(JObject)
    ['{0A559EFE-59E1-429C-BF5E-5E5941B09A32}']
    function getApplicationData : TJavaArray<Byte>; cdecl;                      // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getProtocolInfo : TJavaArray<Byte>; cdecl;                         // ()[B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
  end;

  TJNfcB = class(TJavaGenericImport<JNfcBClass, JNfcB>)
  end;

implementation

type
  JNfcBarcode = interface;

  JNfcBarcodeClass = interface(JObjectClass)
    ['{6C4C2BA6-B3DC-4D6F-B156-FBA56956D54E}']
    function _GetTYPE_KOVIO : Integer; cdecl;                                   //  A: $19
    function _GetTYPE_UNKNOWN : Integer; cdecl;                                 //  A: $19
    function get(tag : JTag) : JNfcBarcode; cdecl;                              // (Landroid/nfc/Tag;)Landroid/nfc/tech/NfcBarcode; A: $9
    function getBarcode : TJavaArray<Byte>; cdecl;                              // ()[B A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
    property TYPE_KOVIO : Integer read _GetTYPE_KOVIO;                          // I A: $19
    property TYPE_UNKNOWN : Integer read _GetTYPE_UNKNOWN;                      // I A: $19
  end;

  [JavaSignature('android/nfc/tech/NfcBarcode')]
  JNfcBarcode = interface(JObject)
    ['{9BA76BC0-0BA3-4984-A94B-ED3BD9D6AF8B}']
    function getBarcode : TJavaArray<Byte>; cdecl;                              // ()[B A: $1
    function getType : Integer; cdecl;                                          // ()I A: $1
  end;

  TJNfcBarcode = class(TJavaGenericImport<JNfcBarcodeClass, JNfcBarcode>)
  end;

const
  TJNfcBarcodeTYPE_KOVIO = 1;
  TJNfcBarcodeTYPE_UNKNOWN = -1;

type
  JNfcF = interface;

  JNfcFClass = interface(JObjectClass)
    ['{0FF1FC55-192E-43E7-BE5C-45C8AC068C61}']
    function get(tag : JTag) : JNfcF; cdecl;                                    // (Landroid/nfc/Tag;)Landroid/nfc/tech/NfcF; A: $9
    function getManufacturer : TJavaArray<Byte>; cdecl;                         // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSystemCode : TJavaArray<Byte>; cdecl;                           // ()[B A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  [JavaSignature('android/nfc/tech/NfcF')]
  JNfcF = interface(JObject)
    ['{C2BAE689-6AFA-4771-AE6F-229A47BB6169}']
    function getManufacturer : TJavaArray<Byte>; cdecl;                         // ()[B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getSystemCode : TJavaArray<Byte>; cdecl;                           // ()[B A: $1
    function getTimeout : Integer; cdecl;                                       // ()I A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
    procedure setTimeout(timeout : Integer) ; cdecl;                            // (I)V A: $1
  end;

  TJNfcF = class(TJavaGenericImport<JNfcFClass, JNfcF>)
  end;

type
  JNfcV = interface;

  JNfcVClass = interface(JObjectClass)
    ['{57BB218E-5320-4417-872D-496D83085687}']
    function get(tag : JTag) : JNfcV; cdecl;                                    // (Landroid/nfc/Tag;)Landroid/nfc/tech/NfcV; A: $9
    function getDsfId : Byte; cdecl;                                            // ()B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getResponseFlags : Byte; cdecl;                                    // ()B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
  end;

  [JavaSignature('android/nfc/tech/NfcV')]
  JNfcV = interface(JObject)
    ['{E087EA77-28F6-447E-857B-AED28FB52EB0}']
    function getDsfId : Byte; cdecl;                                            // ()B A: $1
    function getMaxTransceiveLength : Integer; cdecl;                           // ()I A: $1
    function getResponseFlags : Byte; cdecl;                                    // ()B A: $1
    function transceive(data : TJavaArray<Byte>) : TJavaArray<Byte>; cdecl;     // ([B)[B A: $1
  end;

  TJNfcV = class(TJavaGenericImport<JNfcVClass, JNfcV>)
  end;

type
  JTagTechnology = interface;

  JTagTechnologyClass = interface(JObjectClass)
    ['{79887123-9103-4F45-B75A-71BABD8250C7}']
    function getTag : JTag; cdecl;                                              // ()Landroid/nfc/Tag; A: $401
    function isConnected : boolean; cdecl;                                      // ()Z A: $401
    procedure close ; cdecl;                                                    // ()V A: $401
    procedure connect ; cdecl;                                                  // ()V A: $401
  end;

  [JavaSignature('android/nfc/tech/TagTechnology')]
  JTagTechnology = interface(JObject)
    ['{075DDED4-4B31-49A9-9968-31B205CBF252}']
    function getTag : JTag; cdecl;                                              // ()Landroid/nfc/Tag; A: $401
    function isConnected : boolean; cdecl;                                      // ()Z A: $401
    procedure close ; cdecl;                                                    // ()V A: $401
    procedure connect ; cdecl;                                                  // ()V A: $401
  end;

  TJTagTechnology = class(TJavaGenericImport<JTagTechnologyClass, JTagTechnology>)
  end;

end.
